CREATE TABLE accounts (
	email CHAR(50) NOT NULL UNIQUE PRIMARY KEY,
	password CHAR(50) NOT NULL
);

CREATE TABLE visitors (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone CHAR(15) NOT NULL UNIQUE
);

CREATE TABLE deliveries (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone CHAR(15) NOT NULL UNIQUE,
	email CHAR(50) NOT NULL UNIQUE,
    license_id CHAR(30) NOT NULL UNIQUE,
    company_id INT NOT NULL REFERENCES companies(id)
--  register_date DATETIME NOT NULL
);

CREATE TABLE companies (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
    hot_line CHAR(15) NOT NULL UNIQUE
);

CREATE TABLE vehicles (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    number VARCHAR(10) NOT NULL NOT NULL,
    color VARCHAR(15) NOT NULL,
    type VARCHAR(30) NOT NULL
);

CREATE TABLE visits (
    visitor_id INT NOT NULL PRIMARY KEY REFERENCES visitors(id),
    enter_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    exit_datetime DATETIME NOT NULL,
    unit CHAR(7) NOT NULL,
    vehicle_id INT REFERENCES vehicles(id)
);