### Delete an existing account
POST {{hostname}}/delete
Content-Type: application/json

{
  "accType": "visitor",
  "email": "yes@test.pro",
  "password": "1234"
}

### Register a new account
POST {{hostname}}/register
Content-Type: application/json

{
  "accType": "visitor",
  "email": "yes@test.pro",
  "password": "1234"
}

### Login with correct values
POST {{hostname}}/login
Content-Type: application/json

{
  "email": "yes@test.pro",
  "password": "1234"
}

### Login with non existing email
POST {{hostname}}/login
Content-Type: application/json

{
  "email": "z@z.z",
}

### Login with wrong password
POST {{hostname}}/login
Content-Type: application/json

{
  "email": "yes@test.pro",
  "password": "z"
}